x-worker-base: &worker-base
  build:
    context: ./src/ProjectKubRab/ProjectKubRab.Worker
    dockerfile: Dockerfile
  depends_on:
    dotnetproductspage:
      condition: service_started
    api:
      condition: service_started
    rabbitmq:
      condition: service_healthy
  environment:
    - RabbitMQ__HostName=rabbitmq
    - RabbitMQ__Port=5672
    - RabbitMQ__UserName=app
    - RabbitMQ__Password=app123
    - ProductApi__BaseUrl=http://dotnetproductspage:8080
  networks:
    - public-network

services:
  mongodb:
    image: mongo:8.3.7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    networks:
      - public-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app123
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    networks:
      - public-network
  dotnetproductspage:
    build:
      context: ./src/ProjectKubRab/ProjectKubRab.ProductsWebApp
      dockerfile: Dockerfile
    ports:
      - "8585:8080"
    networks:
      - public-network
  api:
    build:
      context: ./src/ProjectKubRab/ProjectKubRab.API
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - MongoDB__ConnectionString=mongodb://root:root1234@mongodb:27017/?authSource=admin
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=app
      - RabbitMQ__Password=app123
    networks:
      - public-network

  #productspage:
  #  image: nginx:alpine
  #  ports:
  #    - "8181:80"
  #  volumes:
  #    - ./docker/productspage/index.html:/usr/share/nginx/html/index.html:ro
  #  networks:
  #    - public-network
  #reactproductspage:
  #  build:
  #    context: ./src/ProjectKubRab/ProjectKubRab.ProductsWebApp
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3000:80"
  #  networks:
  #    - public-network

  worker-gpu:
    <<: *worker-base
    command: ["MSI RTX 5060 Ti Ventus 2X OC Plus", "MSI GeForce RTX 5070 12G VENTUS 2X OC","ASRock RX 9060 XT CL 16GB AMD Radeon","ASRock RX 9070 XT Challenger AMD 16GB","Asus TUF-RTX 5070 TI 16G GAMING 16GB"]
  worker-cpu:
    <<: *worker-base
    command: ["AMD Ryzen 7 5700X","AMD Ryzen 7 7700X","AMD Ryzen 7 7800X3D","Intel Core i9-14900F","AMD Ryzen 9 9900X3D"]
networks:
  public-network:
    driver: bridge

